# Copyright (C) 2026 Francesco Borra
#

"""Efficiency plotting utilities for bosonic-DM analysis."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

import matplotlib.pyplot as plt

from bosonic_dm.plotting.utils import _DET_TYPE_COLOR


def plot_efficiency_comparison(
    labels_dicts: Mapping[str, tuple],
    interaction: str,
    plot_type: str,
    plot_title: str,
    ylabel: str,
    sharey: bool = True,
    save_path: str | Path | None = None,
) -> tuple[plt.Figure, plt.Axes]:
    """Plot detection efficiency or effective exposure for different detector types.

    Parameters
    ----------
    labels_dicts : Mapping[str, tuple]
        Dictionary of formatted labels and data generated by `build_labels_dicts`.
        Expected format: `selection: (label, ls, marker, means_dict)`.
    interaction : str
        The interaction type (e.g. "axio-electric", "dark-compton"). Used for the title.
    plot_type : str
        Either 'efficiency' or 'eff_exp'. If 'eff_exp', values will be multiplied
        by exposure.
    plot_title : str
        Main title for the plot.
    ylabel : str
        Y-axis label.
    sharey : bool, optional
        Whether subplots should share the same y-axis, by default True.
    save_path : str | Path, optional
        If provided, the plot will be saved to this path.

    Returns
    -------
    tuple[plt.Figure, plt.Axes]
        The generated Matplotlib Figure and Axes objects.
    """
    if plot_type not in ("efficiency", "eff_exp"):
        msg = f"Unknown plot_type '{plot_type}'; expected 'efficiency' or 'eff_exp'"
        raise ValueError(msg)

    fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex=True, sharey=sharey)

    for ax, det_type in zip(axes.flat, _DET_TYPE_COLOR, strict=True):
        color = _DET_TYPE_COLOR[det_type]

        for _, (label, ls, marker, means) in labels_dicts.items():
            enes, vals, uncs = [], [], []

            for ene in sorted(means.keys()):
                entry = means[ene].get(det_type)
                if not entry:
                    continue

                enes.append(ene)

                multiplier = entry["exposure"] if plot_type == "eff_exp" else 1.0

                vals.append(entry["value"] * multiplier)
                uncs.append(entry["unc"] * multiplier)

            if enes:
                ax.errorbar(
                    enes,
                    vals,
                    yerr=uncs,
                    fmt=marker,
                    ls=ls,
                    color=color,
                    label=label,
                    capsize=3,
                )

        ax.set_title(det_type, color=color)
        ax.set_xlabel("Simulated Energy [keV]")
        ax.set_ylabel(ylabel)
        ax.legend()

    fig.suptitle(f"{plot_title} - {interaction}")
    fig.tight_layout()

    if save_path:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=400)

    return fig, axes
