# Copyright (C) 2026 Francesco Borra
#

"""Efficiency plotting utilities for bosonic-DM analysis."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Literal

import matplotlib.pyplot as plt
import numpy as np

from bosonic_dm.plotting.utils import _DET_TYPE_COLOR


def _get_aggregate_categories(labels_dicts: Mapping[str, tuple]) -> list[str]:
    """Return aggregate names in their first-seen order."""
    categories: list[str] = []
    for _, _, _, means in labels_dicts.values():
        for energy in sorted(means):
            for category in means[energy]:
                if category not in categories:
                    categories.append(category)
    return categories


def plot_efficiency_comparison(
    labels_dicts: Mapping[str, tuple],
    interaction: str,
    plot_type: str,
    plot_title: str,
    ylabel: str,
    sharey: bool = True,
    save_path: str | Path | None = None,
    group_by: Literal["detector_type", "detector_group"] = "detector_type",
) -> tuple[plt.Figure, np.ndarray]:
    """Plot efficiency or effective exposure by detector type or detector group.

    Parameters
    ----------
    labels_dicts : Mapping[str, tuple]
        Dictionary of formatted labels and data generated by `build_labels_dicts`.
        Expected format: `selection: (label, ls, marker, means_dict)`.
    interaction : str
        The interaction type (e.g. "axio-electric", "dark-compton"). Used for the title.
    plot_type : str
        Either 'efficiency' or 'eff_exp'. If 'eff_exp', values will be multiplied
        by exposure.
    plot_title : str
        Main title for the plot.
    ylabel : str
        Y-axis label.
    sharey : bool, optional
        Whether subplots should share the same y-axis, by default True.
    save_path : str | Path, optional
        If provided, the plot will be saved to this path.
    group_by
        Select fixed detector-type panels or dynamic panels based on the
        detector-group aggregates in ``labels_dicts``.

    Returns
    -------
    tuple[plt.Figure, np.ndarray]
        The generated Matplotlib Figure and Axes objects.
    """
    if plot_type not in ("efficiency", "eff_exp"):
        msg = f"Unknown plot_type '{plot_type}'; expected 'efficiency' or 'eff_exp'"
        raise ValueError(msg)
    if group_by not in ("detector_type", "detector_group"):
        msg = (
            f"Unknown group_by {group_by!r}; expected 'detector_type' "
            "or 'detector_group'."
        )
        raise ValueError(msg)

    if group_by == "detector_type":
        categories = list(_DET_TYPE_COLOR)
        category_colors = _DET_TYPE_COLOR
    else:
        categories = _get_aggregate_categories(labels_dicts)
        if not categories:
            msg = "No detector-group aggregates are available to plot."
            raise ValueError(msg)
        color_cycle = plt.rcParams["axes.prop_cycle"].by_key()["color"]
        category_colors = {
            category: color_cycle[index % len(color_cycle)]
            for index, category in enumerate(categories)
        }

    n_columns = 2 if len(categories) > 1 else 1
    n_rows = (len(categories) + n_columns - 1) // n_columns
    fig, axes = plt.subplots(
        n_rows,
        n_columns,
        figsize=(12, 4 * n_rows),
        sharex=True,
        sharey=sharey,
        squeeze=False,
    )

    for ax, category in zip(axes.flat, categories, strict=False):
        color = category_colors[category]
        for _, (label, ls, marker, means) in labels_dicts.items():
            enes, vals, uncs = [], [], []

            for ene in sorted(means.keys()):
                entry = means[ene].get(category)
                if not entry:
                    continue

                enes.append(ene)

                multiplier = entry["exposure"] if plot_type == "eff_exp" else 1.0

                vals.append(entry["value"] * multiplier)
                uncs.append(entry["unc"] * multiplier)

            if enes:
                ax.errorbar(
                    enes,
                    vals,
                    yerr=uncs,
                    fmt=marker,
                    ls=ls,
                    color=color,
                    label=label,
                    capsize=3,
                )

        ax.set_title(category, color=color)
        ax.set_xlabel("Simulated Energy [keV]")
        ax.set_ylabel(ylabel)
        handles, _ = ax.get_legend_handles_labels()
        if handles:
            ax.legend()

    for ax in axes.flat[len(categories) :]:
        ax.set_visible(False)

    fig.suptitle(f"{plot_title} - {interaction}")
    fig.tight_layout()

    if save_path:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=400)

    return fig, axes


def plot_fep_survival_fraction(
    labels_dicts: Mapping[str, tuple],
    interaction: str,
    plot_title: str,
    save_path: str | Path | None = None,
    group_by: Literal["detector_type", "detector_group"] = "detector_type",
) -> tuple[plt.Figure, np.ndarray]:
    """Plot FEP survival fraction (SSE and MSE) by detector type or detector group.

    Parameters
    ----------
    labels_dicts : Mapping[str, tuple]
        Dictionary of formatted labels and data generated by `build_labels_dicts`.
    interaction : str
        The interaction type (e.g. "axio-electric", "dark-compton"). Used for the title.
    plot_title : str
        Main title for the plot.
    save_path : str | Path, optional
        If provided, the plot will be saved to this path.
    group_by
        Select fixed detector-type panels or dynamic panels based on the
        detector-group aggregates in ``labels_dicts``.

    Returns
    -------
    tuple[plt.Figure, np.ndarray]
        The generated Matplotlib Figure and Axes objects.
    """
    if group_by not in ("detector_type", "detector_group"):
        msg = (
            f"Unknown group_by {group_by!r}; expected 'detector_type' "
            "or 'detector_group'."
        )
        raise ValueError(msg)

    if group_by == "detector_type":
        categories = list(_DET_TYPE_COLOR)
        category_colors = _DET_TYPE_COLOR
    else:
        categories = _get_aggregate_categories(labels_dicts)
        if not categories:
            msg = "No detector-group aggregates are available to plot."
            raise ValueError(msg)
        color_cycle = plt.rcParams["axes.prop_cycle"].by_key()["color"]
        category_colors = {
            category: color_cycle[index % len(color_cycle)]
            for index, category in enumerate(categories)
        }

    n_columns = 2 if len(categories) > 1 else 1
    n_rows = (len(categories) + n_columns - 1) // n_columns
    fig, axes = plt.subplots(
        n_rows,
        n_columns,
        figsize=(12, 4 * n_rows),
        sharex=True,
        sharey=True,
        squeeze=False,
    )

    if "valid-psd" not in labels_dicts:
        msg = "'valid-psd' selection is missing from labels_dicts."
        raise ValueError(msg)

    _, _, _, means_all = labels_dicts["valid-psd"]
    plot_keys = {
        "sse": ("SSE FEP Survival Fraction", "-", "s"),
        "mse": ("non-SSE FEP Survival Fraction", "--", "^"),
    }

    for ax, category in zip(axes.flat, categories, strict=False):
        color = category_colors[category]

        for key, (label, ls, marker) in plot_keys.items():
            if key not in labels_dicts:
                continue

            _, _, _, means_key = labels_dicts[key]

            enes, vals, uncs = [], [], []

            for ene in sorted(means_all.keys()):
                entry_all = means_all[ene].get(category)
                entry_key = means_key.get(ene, {}).get(category)

                if not entry_all or not entry_key or entry_all["value"] == 0:
                    continue

                enes.append(ene)

                eff_all = entry_all["value"]
                eff_key = entry_key["value"]

                sf = eff_key / eff_all

                rel_unc_all = entry_all["unc"] / eff_all if eff_all > 0 else 0
                rel_unc_key = entry_key["unc"] / eff_key if eff_key > 0 else 0
                sf_unc = sf * np.sqrt(rel_unc_all**2 + rel_unc_key**2)

                vals.append(sf)
                uncs.append(sf_unc)

            if enes:
                ax.errorbar(
                    enes,
                    vals,
                    yerr=uncs,
                    fmt=marker,
                    ls=ls,
                    color=color,
                    label=label,
                    capsize=3,
                    alpha=0.8 if key == "sse" else 0.5,
                )

        ax.set_title(category, color=color)
        ax.set_xlabel("Simulated Energy [keV]")
        ax.set_ylabel("Survival Fraction")
        ax.set_ylim(-0.05, 1.15)
        ax.axhline(1.0, color="grey", linestyle="--", linewidth=0.6)
        handles, _ = ax.get_legend_handles_labels()
        if handles:
            ax.legend()

    for ax in axes.flat[len(categories) :]:
        ax.set_visible(False)

    fig.suptitle(f"{plot_title} - {interaction}")
    fig.tight_layout()

    if save_path:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=400)

    return fig, axes
