schema_version: 1

production:
  version: "v2.1.5"
  reference_root: "/my/local/legend/production"
  metadata_override: null

paths:
  simulation_root: "/my/local/simulation/root"
  data_root: "data/v1"
  inputs_root: "data/inputs"
  plots_root: "plots"
  temporary_root: "tmp"

analysis:
  simulated_energies_keV:
    - 200
    - 500
    - 1000

  fep_window:
    half_width_fwhm: 2.0

  selections:
    - all
    - valid-psd
  apply_lar_veto: true
  detector_groups: "dictionaries/detector-grouping/groups_dict.yaml"

interactions:
  axio-electric:
    job_template: "electron_{energy}keV_hpge_bulk"
    make_lar_survival_plots: false

  dark-compton:
    job_template: "fromfile_dark_compton_{energy}keV_hpge_bulk"
    make_lar_survival_plots: true

background:
  # pet_glob: #if passed override the legend-production folder
  comparison_cut_profile: "without-bb-like"
  energy_ranges_keV:
    - [20, 300]
  bin_widths_keV:
    - 5

output:
  overwrite: false
  save_plots: true
  show_plots: false
  write_manifest: true
